### ISSUE TITLE
BIG ASS WARNING: if 2 sellers are looking at the same buy order ad at the same time right now there's the possibility they can click accept order before the first transaction mines

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#100]
right now it changes the status after the contract is created, it should do it right before

if the status changes disable the button

**Comment by adklempner** [comment]
Sorry, I didn't see you assigned this to yourself. I started working on this issue here: 594a77c

**Comment by adklempner** [comment]
Implemented with #123
