### ISSUE TITLE
anywhere where metamask is used: the ui should display a message saying 'please confirm in metamask'

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#101]
also stuff with longerish delays - where metamask is used
disabling button, displaying loading messages
preventing back button

**Comment by adklempner** [comment]
Check e2e3c93 for reference, I implemented this for the send ether button. It also tells if the user denies a transaction and displays the appropriate message

**Comment by qjflores** [comment]
I've introduced a generic component for this in https://github.com/qjflores/exchangemvpreact/pull/132

i've created a project to keep track of the missing pieces
