### ISSUE TITLE
css styling for Forgot password page

### ISSUE THREAD

**Issue by joshpitzalis** [qjflores/exchangemvpreact#117]
Firebase is super helpful and they send out the emails to handle all this, we just need a design for the page before we can hook it all up.

**Comment by qjflores** [comment]
@sumukhshetty I think this just needs to be something simple a text message, an input box, a submit button.

**Comment by joshpitzalis** [comment]
All of the components are already designed for this page. We have inputs, text widths, font sizing, etc. I can just build using center alignment and the design conventions for elements that are now set. No need to spend time on sketch.

**Comment by sumukhshetty** [comment]
I was just going to tell you the same Josh :)

**Comment by qjflores** [comment]
@joshpitzalis css styling just needs to be applied to this issue and then we can close it
