### ISSUE TITLE
fix the activeescrow id

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#135]
![fix-activeescrow-id](https://cloud.githubusercontent.com/assets/5955676/25400543/87622856-2a25-11e7-9d79-a3e6e09416bb.png)

**Comment by adklempner** [comment]
Is this field even necessary? What does the user gain by knowing the id?

**Comment by qjflores** [comment]
i imagine it being useful in a customer service situation.

@sumukhshetty can you share your perspective?

**Comment by sumukhshetty** [comment]
Customer service is one.
If s buyer has multiple orders, then he will be getting multiple payments, order ID would allow him to know where the payment is coming from. The buyers will put this number in transaction reference.
