### ISSUE TITLE
fix buy orders tab

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#138]
![fix-buy-orders-tab](https://cloud.githubusercontent.com/assets/5955676/25401735/1db2cc7c-2a29-11e7-9ef9-caa783f90a27.png)

**Comment by adklempner** [comment]
2deb8dc fixes last transfer, trustworthiness, and last online

**Comment by qjflores** [comment]
reviewing this screen and the commits - the price/ether is relevant for the user looking at this screen. 

we're not able to correctly display this amount because don't have the price equation set up yet - we ask for the margin on the post trade but currently don't do anything with it.

I think we'll need to get some sort of price equation working before we can implement a "price/ether" feature.

**Comment by adklempner** [comment]
Fixed in #149
