### ISSUE TITLE
fix sell orders tab

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#139]
![fix-sell-orders-tab](https://cloud.githubusercontent.com/assets/5955676/25402528/84eebf84-2a2b-11e7-9c60-26b5b0af03a6.png)

**Comment by qjflores** [comment]
if the lasttransfer doesn't exist put a "-" (dash).

when a trade is completed, update the lasttransfer value

**Comment by adklempner** [comment]
Changed to amount, fixed last transfer, trustworthiness, and last online: 9fff983 . Not sure about the rest: Do you want both the 'Price/Ether' and 'Limits' columns?
