### ISSUE TITLE
fix buyorder awaiting escrow 

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#154]
![fix-buyorder-awaiting-escrow-seller](https://cloud.githubusercontent.com/assets/5955676/25504368/4eef689c-2bd0-11e7-99a6-c56a79f3eeca.png)
![fix-boyorder-awaiting-escrow-buyer](https://cloud.githubusercontent.com/assets/5955676/25504371/4fbc90c4-2bd0-11e7-8243-e7382fc5574f.png)

**Comment by adklempner** [comment]
Fixed everything except cancel trade in #160

Cancel trade is already open in #104
