### ISSUE TITLE
fix negative margin

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#158]
![fix-negative-margin](https://cloud.githubusercontent.com/assets/5955676/25509609/d0ef05d4-2bec-11e7-9153-795408d861d2.png)

**Comment by sumukhshetty** [comment]
Which api are we using to track as of now ? Can they select which market they want to track ? traders generally want a particular markets price like kraken or poloniex

**Comment by adklempner** [comment]
We're using [cryptocompare](https://www.cryptocompare.com/api/#-api-data-price-)

They have an option for getting the average price from one, or several markets.

**Comment by adklempner** [comment]
Ok so what exactly should the input for margin represent?

Right now inputting 1.5 means you're buying/selling for 150% of the market value. 0.5 means you're buying/selling for 50% percent of the market value. Negative numbers shouldn't be used in this case.

The other possibility is inputing 1 means you're buying/selling for 101% of the market value, and inputting -1 means you're buying/selling for 99% of the market value.

Which one should we go with?

**Comment by qjflores** [comment]
I think we should go with whole number and negatives

it wasn't intuitive to put 1.5

**Comment by adklempner** [comment]
Fixed with #161 

Opened separate issue for selecting markets: #162
