### ISSUE TITLE
lato font on other screens @josh

### ISSUE THREAD

**Issue by sumukhshetty** [qjflores/exchangemvpreact#25]

**Comment by joshpitzalis** [comment]
@sumukhshetty The document is rendering Lato for all elements. What page specifically was the harsh typeface appearing on? I don't see it anywhere.

**Comment by sumukhshetty** [comment]
Arseniy is facing the same problem on his localhost, not sure if its an issue with the font being absent from the system or something else. I can send you some screenshots when I do see some issues. But many of the things are much thicker than they are actually in the design

**Comment by joshpitzalis** [comment]
Fixed in https://github.com/qjflores/exchangemvpreact/pull/77. please send screenshots is this problem persists.
