### ISSUE TITLE
start working on static pages

### ISSUE THREAD

**Issue by sumukhshetty** [qjflores/exchangemvpreact#29]

**Comment by joshpitzalis** [comment]
Is this a job for frontend peeps? or does it mean adding redux to the completed frontend work?

**Comment by sumukhshetty** [comment]
I just made a basic css format for the page. We wont have a CMS or anything, so I'll just use the frontend template for the static page and update different pages using that.

**Comment by qjflores** [comment]
i think we need to refine this issue - disect it into specific static pages

The pages that are priority are the ones that arseniy messaged in slack. those are the screens that are blocking him from releasing ether from the seller

**Comment by sumukhshetty** [comment]
Those are part of pre trade flow, will get them done by tomorrow.
By static i mean like about us page, Faq's etc.
Which can have a base format and only need content to put in that base format.
Ive created the base format for it, but I'm getting stuck on git push. Will try and upload using gui

**Comment by joshpitzalis** [comment]
Static page template creates in src/static in pull req https://github.com/qjflores/exchangemvpreact/pull/34. Just clone the master folder for any static pages you want to work on. Alternately, send over designs/content and I can work on them.
