### ISSUE TITLE
blank screen when metamask is not installed

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#40]
![nometamask](https://cloud.githubusercontent.com/assets/5955676/24826085/7acdc060-1c4b-11e7-9878-695360f77de1.png)

- @adklempner connect to some public node instead of localhost:8000. can you decide on what is the best one to connect to and make a pull request? a few that im thinking myetherwallet, infura, our parity node on google cloud
- @sumukhshetty can you create a design for this screen? I'm picturing a screen very similar to the unsupported browser
- @joshpitzalis can you make a pull request with the screen from sumukh?

**Comment by joshpitzalis** [comment]
Sure, just let me know when it's ready.

**Comment by sumukhshetty** [comment]
<img width="591" alt="screen shot 2017-04-19 at 9 48 19 am" src="https://cloud.githubusercontent.com/assets/22879373/25163098/64eaecee-24e5-11e7-80e7-838a2b76ef87.png">

**Comment by joshpitzalis** [comment]
fixed https://github.com/qjflores/exchangemvpreact/pull/145
