### ISSUE TITLE
buyOrders empty state

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#46]
![buyordersemptyscreen](https://cloud.githubusercontent.com/assets/5955676/24828110/0c85af9a-1c74-11e7-9418-0c174dda5585.png)

This screen comes up when there are no available buyorders for sellers to sell to on the exchange

@sumukhshetty - can you create a design for this?
@joshpitzalis - can you make a pull request with the updated design? i can give you access to the firebase console for you to delete buyorders to test this out

**Comment by joshpitzalis** [comment]
@qjflores Firebase access would be fanatstic. 
@sumukhshetty You don't need to give me designs unless you have something specific in mind. I understand the general theme well enough to come up with something basic for empty state.

**Comment by qjflores** [comment]
@joshpitzalis i've given you firebase access

**Comment by sumukhshetty** [comment]
Josh just a basic thing for empty state would do. Maybe something funny if you can, with a note about how we are working on getting more users onboard

**Comment by joshpitzalis** [comment]
fixed https://github.com/qjflores/exchangemvpreact/pull/145
