### ISSUE TITLE
refactor dashboard screen - activetrades component

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#50]
the table doesn't look exactly like the designs - tried to implement a redux reducer for the ActiveTrade component and the table got all messed up

**Comment by joshpitzalis** [comment]
I spent some time cleaning teh css up on this today in pull req https://github.com/qjflores/exchangemvpreact/pull/57 . I didn't build it so I'm not completely familiar with it yet but if you can take a screenshot of 'messed up' and post it here, I can clear it up tomorrow.

**Comment by qjflores** [comment]
![valdatedomnesting](https://cloud.githubusercontent.com/assets/5955676/24890559/2fb88e3a-1e8e-11e7-980c-8e4ebea19f99.png)

The issue involves the styling, the validateDOMNesting warning, and the components with ActiveEscrowListEmptyState and activetrade/layouts/ActiveTrade.

We didn't follow the workflow exactly here with design leading engineering - design was done - html css partially done - then engineering. Now when engineering tries to push this forward there are some issues with the html and css.

**Comment by qjflores** [comment]
@joshpitzalis notes from latest build
![dashboard](https://cloud.githubusercontent.com/assets/5955676/24893618/5ce817ea-1ea2-11e7-98c9-221a83dbfab7.png)

**Comment by joshpitzalis** [comment]
@qjflores Can you please send me login details for firebase. I don't have any data in active escrows to be able to work on this.

**Comment by qjflores** [comment]
@joshpitzalis I'm closing this issue - looks like you've broken this one into much smaller ones
