### ISSUE TITLE
Research and implement firebase security rules

### ISSUE THREAD

**Issue by adklempner** [qjflores/exchangemvpreact#52]
Currently, any authenticated user can modify anything in the database.

Using firebase database rules, it should be possible to restrict what each user has read/write access to and perform validation on data.

**Comment by qjflores** [comment]
@adklempner  starting to get this warning on master when I click on the buy order tab to show sell orders

FIREBASE WARNING: Using an unspecified index. Consider adding ".indexOn": "status"

https://firebase.google.com/docs/database/security/indexing-data

**Comment by adklempner** [comment]
Bolt compiler for writing security rules
[https://github.com/firebase/bolt/blob/master/docs/guide.md](https://github.com/firebase/bolt/blob/master/docs/guide.mdl)

**Comment by qjflores** [comment]
closing this issue

**Comment by adklempner** [comment]
This is a project wide issue, created a project for this
