### ISSUE TITLE
chat module

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#69]

**Comment by joshpitzalis** [comment]
This is probably simple enough for me to build with redux at this point. I could use firebase cloud storage for downloads. What about profile pictures though? There is nowhere for people to upload them at the moment. A default you/other profile picture that can be overwritten if the user object has a profile for google login etc.

**Comment by joshpitzalis** [comment]
@qjflores I never got firebase access. Can you please send it to joshpitzalis@gmail.com and I'll start on this once all the other css work is done. I'll need firebase access to create the message tree and understand how user objects are stored.

**Comment by qjflores** [comment]
@joshptzalis I've outlined how I imagine this module could work, there's room for you to modify this as you see fit. Basically ever sellorder object has a chatroom with a buyer and a seller. The buyer and seller have unique ids that are generated from firebase. The chatroom has messages.

![chatrooms](https://cloud.githubusercontent.com/assets/5955676/25131189/69cd8ff0-2477-11e7-8fba-dd759e3b78fc.png)
![buyorderchatroom](https://cloud.githubusercontent.com/assets/5955676/25131190/6a3517ec-2477-11e7-98ed-9d4f6a93aca2.png)
![sellorderchatroom](https://cloud.githubusercontent.com/assets/5955676/25131191/6a3ab6b6-2477-11e7-9a72-80fc427d2618.png)

i've made example entries in firebase.

feel free to change as you see fit.

**Comment by joshpitzalis** [comment]
built in https://github.com/qjflores/exchangemvpreact/pull/142
