### ISSUE TITLE
screen for non support on mobile

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#70]

**Comment by sumukhshetty** [comment]
Josh, pfa the design 
<img width="350" alt="screen shot 2017-04-19 at 9 39 10 am" src="https://cloud.githubusercontent.com/assets/22879373/25162938/1b4a6340-24e4-11e7-95d8-9be2f3f72bf2.png">

**Comment by sumukhshetty** [comment]
Use this format actually. Center everything. Looks cleaner
<img width="1178" alt="screen shot 2017-03-26 at 9 46 48 pm" src="https://cloud.githubusercontent.com/assets/22879373/25162962/43de1c02-24e4-11e7-9af6-b5e40f651b56.png">

**Comment by sumukhshetty** [comment]
Ignore the last two messages.
This.
<img width="342" alt="screen shot 2017-04-19 at 9 40 35 am" src="https://cloud.githubusercontent.com/assets/22879373/25162973/59556540-24e4-11e7-92c3-bb9ddcb8f6f9.png">

**Comment by joshpitzalis** [comment]
added https://github.com/qjflores/exchangemvpreact/pull/145
