### ISSUE TITLE
make the font thinner for attributes 

### ISSUE THREAD

**Issue by sumukhshetty** [qjflores/exchangemvpreact#73]
<img width="879" alt="screen shot 2017-04-13 at 5 27 13 pm" src="https://cloud.githubusercontent.com/assets/22879373/25003766/a89f5e00-206e-11e7-95a3-d95665d6b693.png">

**Comment by joshpitzalis** [comment]
fixed in https://github.com/qjflores/exchangemvpreact/pull/77.
