### ISSUE TITLE
firebase not linked yet with ads

### ISSUE THREAD

**Issue by sumukhshetty** [qjflores/exchangemvpreact#74]
QJ can we remove dummy data and play around with our accounts.
If i post a trade it doesn't show in the buy or sell screen. Now that account management is sorted seems like we should use our accounts.
Would help us test the site better

**Comment by qjflores** [comment]
@sumukhshetty this fix will come shortly after we merge in the arseniy's branch 'sellorders'. he's got the fix in that branch

**Comment by sumukhshetty** [comment]
Awesome
