### ISSUE TITLE
Footer content needed

### ISSUE THREAD

**Issue by joshpitzalis** [qjflores/exchangemvpreact#78]
There are a lot of links in the footer that just seem like nonsense. There are no screens fo rteh footer on sketch so I don't know what the plan is for content on the footer? Should I just remove everything and keep the copyright with a twitter and facebook logo? If so what are the social media links? If we have links planned what are they?

**Comment by qjflores** [comment]
@joshpitzalis plan is to use use the staticPages component that you created to generate these pages.

for now me can leave them as is

**Comment by sumukhshetty** [comment]
Yeah Josh, leave them as is for now.
Will look into whats absolutely necessary and start creating content for it.
Will get back to you on this, in the next few days.

**Comment by joshpitzalis** [comment]
Sounds good.
