### ISSUE TITLE
Page isnt Underlined with white when selected. 

### ISSUE THREAD

**Issue by sumukhshetty** [qjflores/exchangemvpreact#80]
<img width="983" alt="screen shot 2017-04-17 at 4 03 33 pm" src="https://cloud.githubusercontent.com/assets/22879373/25086729/71609032-2387-11e7-8657-630e56528ba7.png">
If user is on sell page, sell needs to be underlined by the white line
refer to designs

**Comment by joshpitzalis** [comment]
fixed in https://github.com/qjflores/exchangemvpreact/pull/115
