### ISSUE TITLE
When a field is not filled for signup, turn the box red with and exclamation

### ISSUE THREAD

**Issue by sumukhshetty** [qjflores/exchangemvpreact#82]
<img width="256" alt="screen shot 2017-04-17 at 4 07 29 pm" src="https://cloud.githubusercontent.com/assets/22879373/25086790/035feaaa-2388-11e7-9921-b5a802dbb816.png">

**Comment by qjflores** [comment]
I've added required and enabled the default html behavior

**Comment by qjflores** [comment]
default html behavior solves this
