### ISSUE TITLE
content for terms of service

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#87]

**Comment by qjflores** [comment]
@sumukh do we have something for this from the wordpress site?

**Comment by sumukhshetty** [comment]
We can't use that because it was for a centralized exchange. Will set one up for our site.
When do you need it by ?
Would take me around 2 hours

**Comment by sumukhshetty** [comment]
[terms of service.docx](https://github.com/qjflores/exchangemvpreact/files/946107/terms.of.service.docx)
We dont have any registered entity yet, so that needs to be filled in some parts
