### ISSUE TITLE
new screen - replace order detail page

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#97]
when a seller clicks on the sell button from the sell tab replace the current component 

<img width="682" alt="screen shot 2017-04-17 at 3 14 54 pm" src="https://cloud.githubusercontent.com/assets/5955676/25097504/764cfc84-23d7-11e7-8aab-dde2a6692297.png">

with

<img width="419" alt="screen shot 2017-04-17 at 3 35 49 pm" src="https://cloud.githubusercontent.com/assets/5955676/25097623/e28ecc10-23d7-11e7-90ee-9e59d23c337e.png">

instead of 'Send Trade Request' the button would say 'Sell Ether' which then triggers metamask

**Comment by adklempner** [comment]
Done in #112
